#!/bin/bash
# Check if an argument was provided
if [ -z "$1" ]; then
    echo "Please specify the number of random numbers to generate."
    exit 1
fi

# Generate the specified number of random numbers
for i in $(seq 1 $1); do
    echo $(( $(shuf -i 0-20000000 -n 1) - 10000000 ))
done
