#!/bin/bash

# Check if an argument was provided
if [ -z "$1" ]; then
    echo "Please specify the number of random numbers to generate."
    exit 1
fi

# Numero di variabili da creare
n="$1"

# Creazione delle variabili e assegnazione dei numeri casuali
for (( i=1; i<=n; i++ ))
do
    # Nome della variabile
    var="num_$i"
    
    # Assegnazione di un numero casuale alla variabile
    declare "$var"=$(shuf -i 0-20000000 -n 1 | awk '{print $1 - 10000000}')
done

# Lancio di push_swap con le variabili come argomenti
./push_swap $(eval echo "\${num_[@]}")

